### ISSUE TITLE
Missing cmake install section

### ISSUE THREAD

**Issue by arietto** [questdb/c-questdb-client#2]
Hello! Is it reasonable to add install instructions to CMakeLists.txt?

    install(TARGETS 
    c_questdb_client
    c_questdb_client_static 
    line_sender_c_example
    line_sender_cpp_example
    test_line_sender
    DESTINATION ${CMAKE_INSTALL_PREFIX})

    if(UNIX)
    install(TARGETS 
    c_questdb_client_static_pic
    DESTINATION ${CMAKE_INSTALL_PREFIX})
    endif()
Is it possible to use this client library via `find_package`?

**Comment by amunra** [comment]
Currently there's no support for it, but we could add it in going forward.
Right now, we envisage for the library's build steps to be included as part of another project's build sequence to match compiler and settings.

What is your specific use case for requesting this feature, out of curiosity?
