### ISSUE TITLE
No error or write when attempting to write without auth

### ISSUE THREAD

**Issue by jbuckmccready** [questdb/c-questdb-client#45]
Using `questdb-rs 3.0.0` when attempting to connect and write to a QuestDB service that requires authentication no error is returned and no data is written.

Code:
```rust
use questdb::{
    ingress::{Buffer, SenderBuilder},
    Result,
};

fn main() -> Result<()> {
    let mut sender = SenderBuilder::new("127.0.0.1", 9009).connect()?;
    let mut buffer = Buffer::new();
    buffer
        .table("test_table")?
        .column_str("id", "hello world")?
        .column_f64("temperature", 20.0)?
        .column_i64("humidity", 50)?
        .at_now()?;
    sender.flush(&mut buffer)?;
    Ok(())
}
```

QuestDB 7.3.2 service running locally exposed on `9009` but requires authentication (setup using https://questdb.io/docs/reference/api/ilp/authenticate/).

I would expect an error rather than silently failing when attempting to connect to service that requires authentication.

More information:
The table exists with those columns and connecting with authentication or removing authentication requirement from service successfully writes the data to the table. Also if I remove authentication requirement from service and try to connect with authentication I get an error as expected (`Error { code: AuthError, msg: "Did not receive auth challenge. Is the database configured to require authentication?" }`).

**Comment by amunra** [comment]
## The unfortunate news

Currently the protocol doesn't support sending back an error for this from the server.
You need to refer to server logs for this. You might end up with similar issues if you mismatch TLS settings for example.

## The good news

Once you get the client and server settings to match it should all work.

Longer term, we have scheduled improvements for ILP that will feed back more information and avoid these sorts of issues. By current estimates (and I'm bad at estimating), ILP error feedback is queued about 6 months into our current pipeline.
