### ISSUE TITLE
Incomplete ingres documentation

### ISSUE THREAD

**Issue by jerrinot** [questdb/c-questdb-client#61]
[This page](https://docs.rs/questdb-rs/4.0.0/questdb/ingress/index.html) was partially updated to accomodate for ILP@HTTP changes, but it looks incomplete:
1. It says:
    > The ingress module implements QuestDB’s variant of the [InfluxDB Line Protocol](https://questdb.io/docs/reference/api/ilp/overview/) (ILP) over TCP.
  
    This is misleading at best. The client supports both TCP and HTTP transport. The example below this sentence uses the HTTP Transport
2. The paragraph [Connection Security Options](https://docs.rs/questdb-rs/4.0.0/questdb/ingress/index.html#connection-security-options) has a code sample which [links to a URL](https://questdb.io/docs/reference/api/ilp/authenticate) which returns 404:
    <img width="918" alt="image" src="https://github.com/questdb/c-questdb-client/assets/158619/04937707-2ecc-4ddd-aa24-032033882371">
3. The document is silent on configuration, error-handling, retrying, etc. Chances are it's described [elsewhere](https://docs.rs/questdb-rs/4.0.0/questdb/ingress/struct.Sender.html#method.from_conf), but as a Rust developer, I would expect this document to give me an overview of all important concepts.

**Comment by amunra** [comment]
I never ported the Python doc changes to this repo.

The section should probably describe, in order:
* HTTP token auth.
* HTTP basic auth.
* TCP auth.

A bit like here: https://py-questdb-client.readthedocs.io/en/latest/conf.html#authentication

**Comment by jerrinot** [comment]
@mtopolnik another thing I noticed:
<img width="822" alt="image" src="https://github.com/questdb/c-questdb-client/assets/158619/5e588ce5-e8d8-44fd-bed0-cb6fc7ddb55f">


which one is it? maybe both? see? 
```
➜  testrustclient git:(main) ✗ cargo add questdb-rs --features chrono_timestamp
    Updating crates.io index
      Adding questdb-rs v4.0.0 to dependencies.
             Features:
             + chrono
             + chrono_timestamp
 ```
what's the difference between `chrono` and `chrono_timestamp` features?

**Comment by mtopolnik** [comment]
Since our crate doesn't declare the `chrono` feature, but `chrono_timestamp` has it as a dependency, my guess is that this feature is declared in another crate in our dependency tree. However, I couldn't find any such crate using `cargo tree -e feature`.
